language: python

python:
    - 3.5
    - 3.4
    - 2.7
    - nightly
    - pypy
    - pypy3

addons:
    apt:
        packages:
            - python-gdbm
            - python3-gdbm

before_install:
    - sudo service docker restart ; sleep 10  # https://github.com/travis-ci/travis-ci/issues/4778
    - docker run -d --publish=28015:28015 rethinkdb

before_script:
    - pip install . pytest requests

script:
    - py.test -v -s tests
    - py.test -v -s --rethinkdb-servers=localhost tests tests
    - py.test -v -s --rethinkdb-servers=localhost --rethinkdb-big-table tests

